name: nc_flutter_test_bdd_basic_steps
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
